import { supabase } from './supabase';

const ICE_SERVERS = [{ urls: 'stun:stun.l.google.com:19302' }];
let user = null;
let active = null;
let incoming = null;
const channels = new Map();

function addStyles(){if(document.getElementById('ram-audio-call-css'))return;const s=document.createElement('style');s.id='ram-audio-call-css';s.textContent=`.ram-call-overlay{position:fixed;inset:0;z-index:100000;display:grid;place-items:center;background:#0009;font-family:system-ui}.ram-call-card{width:min(360px,calc(100vw - 32px));padding:28px 24px;border-radius:22px;background:#fff;text-align:center;box-shadow:0 20px 70px #0006}.ram-call-avatar{width:76px;height:76px;border-radius:50%;margin:0 auto 14px;display:grid;place-items:center;background:#0b806f;color:#fff;font-size:30px;font-weight:800}.ram-call-card h2{margin:0 0 6px}.ram-call-card p{margin:0 0 18px;color:#667781}.ram-call-status{min-height:20px;color:#667781;font-size:13px;margin-bottom:16px}.ram-call-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}.ram-call-actions button{border:0;border-radius:12px;padding:12px 18px;font-weight:700;cursor:pointer}.ram-call-accept{background:#25d366;color:#fff}.ram-call-reject,.ram-call-end{background:#e74c3c;color:#fff}.ram-call-muted{background:#eee}`;document.head.appendChild(s)}
function removeUI(){document.querySelectorAll('.ram-call-overlay').forEach(x=>x.remove())}
function ui(title,name,statusText){removeUI();const o=document.createElement('div');o.className='ram-call-overlay';o.innerHTML=`<div class="ram-call-card"><div class="ram-call-avatar">${(name||'?').trim().charAt(0).toUpperCase()}</div><h2>${title}</h2><p>${name||'Contact'}</p><div class="ram-call-status" id="ram-call-status">${statusText||''}</div><div class="ram-call-actions" id="ram-call-actions"></div></div></div>`;document.body.appendChild(o)}
function setActions(items){const box=document.getElementById('ram-call-actions');if(!box)return;box.innerHTML='';items.forEach(([text,cls,fn])=>{const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;box.appendChild(b)})}
function setStatus(t){const x=document.getElementById('ram-call-status');if(x)x.textContent=t}
function remoteAudio(){let a=document.getElementById('ram-remote-audio');if(!a){a=document.createElement('audio');a.id='ram-remote-audio';a.autoplay=true;a.playsInline=true;a.setAttribute('playsinline','');a.style.display='none';document.body.appendChild(a)}return a}
async function chats(){const {data,error}=await supabase.rpc('get_my_chats');if(error)throw error;return data||[]}
async function getChannel(chat){if(channels.has(chat.chat_id))return channels.get(chat.chat_id);const ch=supabase.channel(`call-${chat.chat_id}`);ch.on('broadcast',{event:'ring'},p=>ringReceived(chat,p.payload)).on('broadcast',{event:'offer'},p=>offerReceived(chat,p.payload)).on('broadcast',{event:'answer'},p=>answerReceived(chat,p.payload)).on('broadcast',{event:'ice'},p=>iceReceived(chat,p.payload)).on('broadcast',{event:'reject'},p=>rejectReceived(chat,p.payload)).on('broadcast',{event:'hangup'},p=>hangupReceived(chat,p.payload));await new Promise((resolve,reject)=>ch.subscribe(state=>{if(state==='SUBSCRIBED')resolve();if(state==='CHANNEL_ERROR'||state==='TIMED_OUT')reject(new Error('Call signaling unavailable'))}));channels.set(chat.chat_id,{chat,ch});return channels.get(chat.chat_id)}
async function send(chat,event,payload){const c=await getChannel(chat);return c.ch.send({type:'broadcast',event,payload})}
async function getMicrophone(){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone API available nahi hai. Ram Chat ko HTTPS/secure browser me kholen.');let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});}catch(e){if(e.name==='NotFoundError'||e.name==='DevicesNotFoundError')throw new Error('Microphone device nahi mila. Windows Sound Settings me Input microphone select karke Chrome restart karein.');if(e.name==='NotAllowedError'||e.name==='PermissionDeniedError')throw new Error('Microphone permission denied. Chrome me Ram Chat ke microphone ko Allow karein.');throw new Error(e.message||'Microphone access failed.')}return stream}
async function makePeer(chat){const pc=new RTCPeerConnection({iceServers:ICE_SERVERS});const stream=await getMicrophone();stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const a=remoteAudio();a.srcObject=e.streams[0];a.play().catch(()=>setStatus('Connected — speaker/audio allow karein'))};pc.onicecandidate=e=>{if(e.candidate)send(chat,'ice',{from:user.id,candidate:e.candidate.toJSON?.()||e.candidate}).catch(()=>{})};active={chat,pc,stream,candidates:[]};return pc}
async function start(chat){if(active||incoming)return;try{await getChannel(chat);ui('Calling…',chat.other_display_name||chat.other_username,'Microphone connect ho raha hai…');setActions([['End','ram-call-end',()=>end(true)]]);const pc=await makePeer(chat);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await send(chat,'ring',{from:user.id});await send(chat,'offer',{from:user.id,offer});setStatus('Waiting for answer…')}catch(e){console.error(e);cleanup();alert(e?.message||'Audio call start nahi ho saki.')}}
async function ringReceived(chat,p){if(mine(p)||active||incoming)return;incoming={chat,offer:null};ui('Incoming audio call',chat.other_display_name||chat.other_username,'Calling you…');setActions([['Accept','ram-call-accept',accept],['Reject','ram-call-reject',reject]])}
async function offerReceived(chat,p){if(mine(p)||active)return;if(!incoming||incoming.chat.chat_id!==chat.chat_id)incoming={chat,offer:null};incoming.offer=p.offer;if(document.querySelector('.ram-call-overlay'))setStatus('Incoming call');else{ui('Incoming audio call',chat.other_display_name||chat.other_username,'Calling you…');setActions([['Accept','ram-call-accept',accept],['Reject','ram-call-reject',reject]])}}
async function accept(){if(!incoming?.offer)return setStatus('Waiting for call data…');const {chat,offer}=incoming;try{const pc=await makePeer(chat);await pc.setRemoteDescription(offer);for(const c of active.candidates.splice(0))await pc.addIceCandidate(c).catch(()=>{});const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await send(chat,'answer',{from:user.id,answer});incoming=null;ui('Audio call',chat.other_display_name||chat.other_username,'Connected');setActions([['Mute','ram-call-muted',mute],['End','ram-call-end',()=>end(true)]]);}catch(e){console.error(e);cleanup();alert(e?.message||'Call accept nahi ho saki.')}}
async function answerReceived(chat,p){if(mine(p)||!active||active.chat.chat_id!==chat.chat_id)return;try{await active.pc.setRemoteDescription(p.answer);for(const c of active.candidates.splice(0))await active.pc.addIceCandidate(c).catch(()=>{});setStatus('Connected')}catch(e){console.error(e)}}
async function iceReceived(chat,p){if(mine(p))return;if(!active||active.chat.chat_id!==chat.chat_id||!active.pc.remoteDescription){if(active&&active.chat.chat_id===chat.chat_id)active.candidates.push(p.candidate);return}await active.pc.addIceCandidate(p.candidate).catch(()=>{})}
async function reject(){if(!incoming)return;await send(incoming.chat,'reject',{from:user.id}).catch(()=>{});incoming=null;removeUI()}
function rejectReceived(chat,p){if(mine(p)||!active||active.chat.chat_id!==chat.chat_id)return;setStatus('Call rejected');setTimeout(cleanup,700)}
function hangupReceived(chat,p){if(mine(p))return;if((active&&active.chat.chat_id===chat.chat_id)||(incoming&&incoming.chat.chat_id===chat.chat_id))cleanup()}
function mute(){const t=active?.stream?.getAudioTracks?.()[0];if(!t)return;t.enabled=!t.enabled;const b=[...document.querySelectorAll('.ram-call-actions button')].find(x=>x.textContent==='Mute'||x.textContent==='Unmute');if(b)b.textContent=t.enabled?'Mute':'Unmute'}
async function end(notify){const chat=active?.chat||incoming?.chat;if(notify&&chat)await send(chat,'hangup',{from:user.id}).catch(()=>{});cleanup()}
function cleanup(){if(active){active.stream.getTracks().forEach(t=>t.stop());active.pc.close()}active=null;incoming=null;removeUI();const a=document.getElementById('ram-remote-audio');if(a)a.srcObject=null}
async function currentChat(){const small=document.querySelector('.chat-head small');const m=small?.textContent?.match(/^@([^\s·]+)/);if(!m)return null;const list=await chats();return list.find(c=>c.other_username===m[1])||null}
function bind(){document.querySelectorAll('.audio-call-icon').forEach(btn=>{if(btn.dataset.ramAudioBound)return;btn.dataset.ramAudioBound='1';btn.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();const chat=await currentChat();if(!chat)return alert('Chat load nahi hua.');await start(chat)})})}
async function init(){addStyles();const {data}=await supabase.auth.getUser();user=data?.user;if(!user)return;try{for(const c of await chats())getChannel(c).catch(console.error)}catch(e){console.error(e)}bind();new MutationObserver(bind).observe(document.body,{childList:true,subtree:true})}
setTimeout(init,500);window.addEventListener('beforeunload',()=>{cleanup();channels.forEach(x=>supabase.removeChannel(x.ch))});